Задания третьего вебинара
js-tasks-ru/vue-20210304_allenwalker12349 pull request #3
Opened 2021-03-28 15:25 UTC by allenwalker12349

2021-03-28 15:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-03-28 15:38 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-03-28 20:14 UTC, ShGKme requested changes
Требуются небольшие исправления в:
- [x] 02-components/01-CounterButtonComponent
- [x] 02-components/06-MeetupView

Остальные задачи приняты.

2021-03-28 20:14 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/index.html
> +  <p><counter-button v-model="count2" @increment="count2 = $event" :count="count2"></counter-button> - count = {{ count2 }}</p>
В компоненте требуется описать модель, чтобы работала директива `v-model`.

Документация: https://vuejs.org/v2/api/#model

Гайд из документации: https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

Пример с вебинара по этой теме: https://github.com/js-tasks-ru/vue-course-materials/blob/master/02-
components/02-MeetupsPage/FormCheck.js

2021-03-28 20:14 UTC, ShGKme commented on 02-components/06-MeetupView/MeetupView.js
> +  },
`this.meetup.imageId` может быть `null`. В этом случае ссылка будет некорректной.

Кроме того, это точно не данные компонента, не его состояние, а результат вычисления на основе других его данных - данных митапа из входного параметра. Если родитель обновит данные входного параметра, то здесь ссылка не обновится.

Здесь требуется вычисляемое свойство.

2021-04-02 19:36 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-04-02 21:20 UTC, ShGKme requested changes
Требуется небольшое исправление.

На забудьте потом обновить файлы в следующей задаче, либо явно импортировать компонент из соседней задачи.

2021-04-02 21:20 UTC, ShGKme commented on 02-components/06-MeetupView/MeetupView.js
> +    },
Та же проблема, что была раньше. Если `this.meetup.imageId === null`, то ссылка получается некорректная... Требуется проверка.

2021-04-03 09:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-04-03 11:33 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-04-03 18:13 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-04-03 18:13 UTC, ShGKme commented on 03-sfc/02-FormGroup/components/FormGroup.vue
> +  <div class="form-group" :class="inline ? 'form-group_inline' : ''">
Часто требуется устанавливать класс по определённому условию. Для этого во Vue есть возможность привязывать классы объектом, где ключ - класс, а значение - условие.
`:class="{ 'form-group_inline': inline }"`

2021-04-03 18:14 UTC, merged